// APP
export const SET_INITIALIZATION = 'SET_INITIALIZATION'
export const SWITCH_CONSTRUCTION = 'SWITCH_CONSTRUCTION'
export const NIGHTMODE_RELAY = 'NIGHTMODE_RELAY'
export const HIDE_FOOTER = "HIDE_FOOTER"

// AUTH
export const GET_CAPTCHA = 'GET_CAPTCHA'
export const LOGIN_FETCH = "LOGIN_FETCH"
export const FALSY_DATA = "FALSY_DATA"
export const SET_MY_DATA = 'SET_MY_DATA'
export const LOG_STATUS = 'LOG_STATUS'
export const DELETE = 'DELETE'
export const ERROR_CODE_MESSAGE = "PRE_LOG_STATUS"

//DIALOGS
export const ADD_MESSAGE = 'ADD_MESSAGE'

//PROFILE
export const CURRENT_PROFILE = 'CURRENT_PROFILE'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const DATA_RECEIVED = 'DATA_RECEIVED'
export const SET_PHOTO = 'SET_PHOTO'
export const SET_AVATAR = 'SET_AVATAR'
export const IS_FETCHING = 'IS_FETCHING'
export const SET_RESULT = 'SET_RESULT'
export const SET_NOTFOUND = 'SET_NOTFOUND'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const STATUS_ERROR = 'STATUS_ERROR'
export const SET_STATUS = 'SET_STATUS'
export const ADD_POST = 'ADD_POST'

//USERS
export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const SET_USERS = 'SET_USERS'
export const FETCH = 'FETCH'
export const SET_PAGE = 'SET_PAGE'
export const FOLLOWING_PROGRESS = 'FOLLOWING_PROGRESS'